name: GitHub Pages

on:
  push:
    branches:
    - master

permissions:
    actions: read
    checks: read
    contents: read
    deployments: read
    id-token: write
    issues: read     
    pull-requests: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout
      uses: actions/checkout@v4.1.4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
  
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build:prod

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5

    - name: Deploy
      if: success()
      uses: actions/deploy-pages@v4.0.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/
        enable_jekyll: true
