name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
  
    - name: Checkout
      uses: actions/checkout@v4.1.4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
  

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build:prod

    - name: Deploy
      if: success()
      uses: actions/deploy-pages@v4.0.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/
        enable_jekyll: true
